---


playbook_tag: selenoid-test # same for all instances created with this playbook
key_name: selenoid-test # same for all instances created with this playbook
ansible_ssh_private_key_file: "~/.ssh/{{ key_name }}-private.pem" # where to store generated key

use_public_ip: false
instance_type: t2.micro
security_group: test
vpc_subnet_id: subnet-b37f5dee
image: ami-43a15f3e
region: us-east-1