#demo1.yml

- name: Start sandbox instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: mbp
    instance_type: t2.micro
    security_group: test
    image: ami-ee6f5e8b
    region: us-east-2
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}" 
        groupname: launched
      with_items: "{{ ec2.instances }}"
    
    - name: Save instance address 
      local_action: copy content={{ item.public_dns_name }} dest=/Users/dmitrykuzmin/dev/tests/ansible/hosts
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 5
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"



- name: Configure instance(s) 1
  hosts: all
  remote_user: ubuntu
  become: True
  gather_facts: True
  tasks:
    - name: Install docker
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - docker.io

- name: Configure instance(s) 2
  hosts: all
  remote_user: ubuntu
  become: True
  gather_facts: True
  roles:
    - selenoid
