#stop all ec2 instance

- name: Terminate sandbox instances
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Termonate instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         exact_count: 0
         count_tag:
            Playbook: "{{ playbook_tag }}"
            Suite: "{{ suite_tag }}"
         instance_tags:
            Playbook: "{{ playbook_tag }}"
            Suite: "{{ suite_tag }}"

    - name: Delete all "{{ suite_tag }}" hosts
      file: path={{ item }} state=absent
      with_fileglob: "./hosts/host-{{ suite_tag }}-*"
