---


- name: Selenoid | Create video folder
  file:
    path: "{{ selenoid_video_host_output_dir }}"
    state: directory
    mode: 0755

- name: Selenoid | Upload CM
  copy:
    src: "{{ role_path }}/cm"
    dest: /bin/cm
    mode: 777

- name: Selenoid | Run CM
  raw:  >
    cm selenoid start
    --vnc
    --config-dir {{ selenoid_config_dir }}
    --tmpfs {{ selenoid_tmpfs }}
    --browsers {% for browser in selenoid_browsers -%}{{ browser }}{%- if not loop.last -%},{%- endif -%}{%- endfor %}
    --last-versions {{ selenoid_browsers_last_versions }}
    --vnc
    --args "-limit {{ selenoid_limit }} -listen :{{ selenoid_listen_port }} -video-output-dir={{ selenoid_video_container_output_dir }} -conf /etc/selenoid/browsers.json"
    