---


- name: Selenoid | Create video folder
  file:
    path: "{{ selenoid_video_host_output_dir }}"
    state: directory
    mode: 0755

- name: Selenoid | Upload CM
  copy:
    src: "{{ role_path }}/cm"
    dest: /bin/cm
    mode: 777

- name: Selenoid | Create config dir
  file:
    path: "{{ selenoid_config_dir }}"
    state: directory
    mode: 0777

- name: Selenoid | Upload browsers.json
  copy:
    src: "{{ role_path }}/browsers.json"
    dest: "{{ selenoid_config_dir }}/browsers.json"
    mode: 777

- name: Selenoid | Pull browsers
  raw:  >
    docker pull selenoid/vnc:chrome_64.0 &&
    docker pull selenoid/vnc:chrome_53.0 &&
    docker pull selenoid/vnc:firefox_47.0

- name: Selenoid | Run CM
  raw:  >
    cm selenoid start
    --vnc
    --config-dir {{ selenoid_config_dir }}
    --tmpfs {{ selenoid_tmpfs }}
    --args "-limit {{ selenoid_limit }} -listen :{{ selenoid_listen_port }} -video-output-dir={{ selenoid_video_container_output_dir }} -timeout 3m0s -session-delete-timeout 3m0s -conf /etc/selenoid/browsers.json"
    